<?php

/**
 * @phpstan-type ShapeEntityTagConnection array{
 *     rowid?: int,
 *     context: string,
 *     connected_id: int,
 *     tag_id: int,
 * }
 *
 * @property ?int $rowid (auto_increment)
 * @property ?string $context
 * @property ?int $connected_id
 * @property ?int $tag_id
 *
 * @extends SQLEntity<ShapeEntityTagConnection>
 */
class EntityTagConnection extends SQLEntity
{
	public const string TABLE_NAME = 'tag_connections';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTagConnection $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTagConnection $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTagConnection $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTagConnection $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityTagConnection $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityTagConnection $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
