<?php

/**
 * @phpstan-type ShapeEntityRichtext array{
 *     id?: int,
 *     content_type: string,
 *     locale?: string,
 *     name?: string|null,
 *     title?: string|null,
 *     content?: string|null,
 *     __content?: string|null,
 * }
 *
 * @property ?int $id (auto_increment)
 * @property ?string $content_type
 * @property ?string $locale
 * @property ?string $name
 * @property ?string $title
 * @property ?string $content
 * @property ?string $__content
 *
 * @extends SQLEntity<ShapeEntityRichtext>
 */
class EntityRichtext extends SQLEntity
{
	public const string TABLE_NAME = 'richtext';

	// ============================================================================
	// Custom methods (safe from regeneration)
	// ============================================================================

	public const int ERROR_MULTIPLE = -2;
	public const int ERROR_NOT_FOUND = -3;

	public static function getContentTitle(int $id): string
	{
		return static::pluckFirst('title', ['id' => $id]) ?? '';
	}

	public static function getContentLocale(int $id): ?string
	{
		if (!RichTextLocaleService::hasRichTextLocaleColumn()) {
			return null;
		}

		$locale = static::pluckFirst('locale', ['id' => $id]);

		return is_string($locale) ? LocaleService::tryCanonicalize($locale) : null;
	}

	public static function getContentList(): array
	{
		return DbHelper::selectMany('richtext');
	}

	public static function getContentIdByName(mixed $name, ?string $locale = null): int
	{
		$where = ['name' => trim((string) $name)];
		$locale = $locale !== null ? LocaleService::tryCanonicalize($locale) : null;

		if ($locale !== null && RichTextLocaleService::hasRichTextLocaleColumn()) {
			$where['locale'] = $locale;
		}

		$data = DbHelper::selectMany('richtext', $where, false, '', 'id');

		if (count($data) > 1) {
			return self::ERROR_MULTIPLE;
		}

		return $data[0]['id'] ?? self::ERROR_NOT_FOUND;
	}

	public static function getAllModificationsData(int $id): ?array
	{
		if (!class_exists(History::class)) {
			return null;
		}

		return History::getAllModificationsWithComments('richtext', $id);
	}

	public static function getListForSelect(?string $locale = null, ?int $currentId = null, bool $appendLocale = false): array
	{
		$return = [];
		$params = [];
		$where = '';
		$locale = $locale !== null ? LocaleService::tryCanonicalize($locale) : null;
		$has_locale_column = RichTextLocaleService::hasRichTextLocaleColumn();

		if ($locale !== null && $has_locale_column) {
			$where = 'WHERE `locale` = ?';
			$params[] = $locale;

			if ($currentId !== null && $currentId > 0) {
				$where .= ' OR `id` = ?';
				$params[] = $currentId;
			}
		}

		$info_contents = DbHelper::selectManyFromQuery("SELECT * FROM richtext {$where} ORDER BY title", $params);

		foreach ($info_contents as $value) {
			$value_locale = $has_locale_column
				? LocaleService::tryCanonicalize((string) ($value['locale'] ?? '')) ?? ''
				: '';
			$label = (string) ($value['name'] ?? '');

			if ($value_locale !== '' && ($appendLocale || ($locale !== null && $value_locale !== $locale))) {
				$label .= ' (' . $value_locale . ')';
			}

			$return[] = [
				'inputtype' => 'option',
				'value' => $value['id'],
				'label' => $label,
			];
		}

		return $return;
	}

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityRichtext $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityRichtext $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityRichtext $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityRichtext $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityRichtext $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityRichtext $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
