<?php

declare(strict_types=1);

class I18nCatalogBuilder
{
	/**
	 * Build catalog PHP files for all locales, or for a single locale if specified.
	 *
	 * @return list<string> built locale codes
	 */
	public static function build(string $localeFilter = ''): array
	{
		$outputDir = DEPLOY_ROOT . 'generated/i18n/';

		if (!is_dir($outputDir)) {
			mkdir($outputDir, 0o755, true);
		}

		$locales = $localeFilter !== ''
			? [LocaleService::canonicalize($localeFilter)]
			: self::_getAllLocales();

		self::_removeLegacyCatalogFiles($outputDir, $locales);

		foreach ($locales as $locale) {
			self::_buildLocale($locale, $outputDir);
		}

		return $locales;
	}

	private static function _buildLocale(string $locale, string $outputDir): void
	{
		$locale = LocaleService::canonicalize($locale);
		$storage_locales = self::_getStorageLocaleAliases($locale);
		$placeholders = implode(', ', array_fill(0, count($storage_locales), '?'));
		$pdo = Db::instance();

		$stmt = $pdo->prepare(
			"SELECT m.domain, m.`key`, m.context, t.locale, t.text
			FROM i18n_messages m
			JOIN i18n_translations t ON t.domain = m.domain AND t.`key` = m.`key` AND t.context = m.context
			WHERE t.locale IN ({$placeholders}) AND TRIM(t.text) <> ''
			ORDER BY m.domain, m.`key`, m.context, CASE WHEN t.locale = ? THEN 0 ELSE 1 END"
		);
		$stmt->execute([...$storage_locales, $locale]);
		$rows = $stmt->fetchAll(\PDO::FETCH_ASSOC);

		$catalog = [];

		foreach ($rows as $row) {
			$flatKey = $row['domain'] . '.' . $row['key'];

			if ($row['context'] !== '') {
				$flatKey .= '.' . $row['context'];
			}

			// BCP 47 catalog rows win over legacy storage aliases. The SQL order
			// makes this deterministic; the condition keeps the rule explicit.
			if (!isset($catalog[$flatKey]) || $row['locale'] === $locale) {
				$catalog[$flatKey] = $row['text'];
			}
		}

		$hash = md5(serialize($catalog));
		$path = $outputDir . $locale . '.php';

		$php = "<?php\n// Generated by radaptor i18n:build — do not edit\nreturn " . var_export($catalog, true) . ";\n";
		file_put_contents($path, $php);

		// Update build state — use raw PDO; i18n_build_state has a string PK which
		// confuses the audit trigger that expects an integer row_id.
		$pdo->prepare(
			"INSERT INTO i18n_build_state (locale, catalog_hash, built_at)
			VALUES (?, ?, ?)
			ON DUPLICATE KEY UPDATE catalog_hash = VALUES(catalog_hash), built_at = VALUES(built_at)"
		)->execute([$locale, $hash, date('Y-m-d H:i:s')]);
	}

	/**
	 * @return list<string>
	 */
	private static function _getAllLocales(): array
	{
		$rows = DbHelper::selectMany('i18n_translations', []);
		$locales = [];

		foreach (array_column($rows, 'locale') as $locale) {
			$canonical = LocaleService::tryCanonicalize((string) $locale);

			if ($canonical !== null) {
				$locales[$canonical] = true;
			}
		}

		$locales = array_keys($locales);
		sort($locales);

		return $locales;
	}

	/**
	 * @param list<string> $locales
	 */
	private static function _removeLegacyCatalogFiles(string $outputDir, array $locales): void
	{
		foreach ($locales as $locale) {
			$canonical = LocaleService::canonicalize($locale);
			$legacy = LocaleService::toIntlLocale($canonical);
			$legacy_path = $outputDir . $legacy . '.php';

			if ($legacy !== $canonical && is_file($legacy_path)) {
				unlink($legacy_path);
			}
		}
	}

	/**
	 * @return list<string>
	 */
	private static function _getStorageLocaleAliases(string $locale): array
	{
		$canonical = LocaleService::canonicalize($locale);
		$aliases = [$canonical => true];
		$legacy = LocaleService::toIntlLocale($canonical);

		if ($legacy !== $canonical) {
			$aliases[$legacy] = true;
		}

		return array_keys($aliases);
	}
}
