<?php

/**
 * @phpstan-type ShapeEntityI18n_messag array{
 *     domain: string,
 *     key: string,
 *     context?: string,
 *     source_text?: string,
 *     source_hash?: string,
 *     metadata?: string|null,
 * }
 *
 * @property ?string $domain
 * @property ?string $key
 * @property ?string $context
 * @property ?string $source_text
 * @property ?string $source_hash
 * @property ?string $metadata
 *
 * @extends SQLEntity<ShapeEntityI18n_messag>
 */
class EntityI18n_messag extends SQLEntity
{
	public const string TABLE_NAME = 'i18n_messages';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_messag $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_messag $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_messag $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_messag $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityI18n_messag $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_messag $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
