<?php

/**
 * @phpstan-type ShapeEntityI18n_build_state array{
 *     locale: string,
 *     catalog_hash: string,
 *     built_at: string,
 * }
 *
 * @property ?string $locale
 * @property ?string $catalog_hash
 * @property ?string $built_at
 *
 * @extends SQLEntity<ShapeEntityI18n_build_state>
 */
class EntityI18n_build_state extends SQLEntity
{
	public const string TABLE_NAME = 'i18n_build_state';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_build_state $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_build_state $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_build_state $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_build_state $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityI18n_build_state $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_build_state $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
