<?php

/**
 * @phpstan-type ShapeEntityI18n_translation array{
 *     domain: string,
 *     key: string,
 *     context?: string,
 *     locale: string,
 *     text?: string,
 *     human_reviewed?: int|bool,
 *     allow_source_match?: int|bool,
 *     source_hash_snapshot?: string,
 * }
 *
 * @property ?string $domain
 * @property ?string $key
 * @property ?string $context
 * @property ?string $locale
 * @property ?string $text
 * @property int|bool|null $human_reviewed
 * @property int|bool|null $allow_source_match
 * @property ?string $source_hash_snapshot
 *
 * @extends SQLEntity<ShapeEntityI18n_translation>
 */
class EntityI18n_translation extends SQLEntity
{
	public const string TABLE_NAME = 'i18n_translations';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_translation $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_translation $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_translation $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_translation $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityI18n_translation $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_translation $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
