<?php

/**
 * @phpstan-type ShapeEntityI18n_tm_entry array{
 *     tm_id?: int,
 *     source_locale: string,
 *     target_locale: string,
 *     source_text_normalized: string,
 *     source_text_raw: string,
 *     target_text: string,
 *     domain?: string,
 *     source_key?: string,
 *     context?: string,
 *     source_hash: string,
 *     usage_count?: int,
 *     quality_score?: string,
 *     created_by?: int|null,
 *     updated_by?: int|null,
 *     created_at: string,
 *     updated_at: string,
 * }
 *
 * @property ?int $tm_id (auto_increment)
 * @property ?string $source_locale
 * @property ?string $target_locale
 * @property ?string $source_text_normalized
 * @property ?string $source_text_raw
 * @property ?string $target_text
 * @property ?string $domain
 * @property ?string $source_key
 * @property ?string $context
 * @property ?string $source_hash
 * @property ?int $usage_count
 * @property ?string $quality_score
 * @property ?int $created_by
 * @property ?int $updated_by
 * @property ?string $created_at
 * @property ?string $updated_at
 *
 * @extends SQLEntity<ShapeEntityI18n_tm_entry>
 */
class EntityI18n_tm_entry extends SQLEntity
{
	public const string TABLE_NAME = 'i18n_tm_entries';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|array<string, mixed> $id
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public static function updateById(int|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityI18n_tm_entry $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
