<?php assert(isset($this) && $this instanceof Template); ?>
<?php
$this->registerLibrary('STIMULUS_LOADER');
$this->registerLibrary('TIPPY');

$form_id = (string)($this->props['form_id'] ?? '');
$editmode_form_target_id = trim((string)($this->props['editmode_form_target_id'] ?? ''));
$action = (string)($this->props['action'] ?? '');
$method = (string)($this->props['method'] ?? 'post');
$form_class = trim((string)($this->props['form_class'] ?? ''));
$form_classes = trim('autogenerated ' . $form_class);
$autocomplete = (bool)($this->props['autocomplete'] ?? true);
$title = (string)($this->props['title'] ?? '');
$sub_title = (string)($this->props['sub_title'] ?? '');
$button_save = is_array($this->props['button_save'] ?? null) ? $this->props['button_save'] : null;
$button_cancel = is_array($this->props['button_cancel'] ?? null) ? $this->props['button_cancel'] : null;
$post_javascript_file = (string)($this->props['post_javascript_file'] ?? '');
$focusable = (bool)($this->props['focusable'] ?? true);
$html_attributes = is_array($this->props['html_attributes'] ?? null) ? $this->props['html_attributes'] : [
	'data-controller' => 'form-timezone',
];
$submit_context = is_array($this->props['submit_context'] ?? null) ? $this->props['submit_context'] : [];

$html_attributes_string = '';

foreach ($html_attributes as $attribute_name => $attribute_value) {
	if (!is_string($attribute_name) || $attribute_name === '') {
		continue;
	}

	if ($attribute_value === null || $attribute_value === false) {
		continue;
	}

	if ($attribute_value === true) {
		$html_attributes_string .= ' ' . $attribute_name;

		continue;
	}

	$html_attributes_string .= ' ' . $attribute_name . '="' . e((string)$attribute_value) . '"';
}
?>
<?php if ($editmode_form_target_id !== ''): ?>
	<div id="<?= e($editmode_form_target_id) ?>" data-form-editor-form-target>
<?php endif; ?>
<form id="<?= e($form_id) ?>" action="<?= e($action) ?>" method="<?= e($method) ?>" class="<?= e($form_classes) ?>"<?= !$autocomplete ? ' autocomplete="off"' : '' ?><?= $html_attributes_string ?>>
	<?php if ($title !== ''): ?>
		<div class="subheader">
			<h1><?= e($title) ?></h1>
			<br class="cleaner">
		</div>
	<?php endif; ?>

	<?php if ($sub_title !== ''): ?>
		<h2><?= e($sub_title) ?></h2>
	<?php endif; ?>

		<?php foreach ($submit_context as $context_name => $context_value): ?>
			<input type="hidden" name="<?= e(FormSubmitContext::htmlFieldName((string)$context_name)) ?>" value="<?= e((string)$context_value) ?>">
		<?php endforeach; ?>
		<?= $this->fetchContent('hidden_fields') ?>
	<?= $this->fetchContent('rows') ?>

	<div style="text-align:center;" class="button-container buttons">
		<?php if (is_array($button_save)): ?>
			<button class="submit_button <?= e((string)($button_save['class'] ?? '')) ?>" name="submit_button" value="<?= AbstractForm::_SUBMIT_VALUE_SAVE ?>" type="submit">
				<?= Icons::get($button_save['icon'] ?? IconNames::FORM_SAVE) ?>
				<?= e((string)($button_save['text'] ?? 'Save')) ?>
			</button>
		<?php endif; ?>

		<?php if (is_array($button_cancel)): ?>
			<button style="float:left;" class="submit_button <?= e((string)($button_cancel['class'] ?? '')) ?>" name="submit_button" value="<?= AbstractForm::_SUBMIT_VALUE_CANCEL ?>" type="submit">
				<?= Icons::get($button_cancel['icon'] ?? IconNames::FORM_CANCEL) ?>
				<?= e((string)($button_cancel['text'] ?? 'Cancel')) ?>
			</button>
		<?php endif; ?>
	</div>
	<div style="clear:both"></div>
</form>

<?= $this->fetchContent('post_form_chrome') ?>

<?php if ($editmode_form_target_id !== ''): ?>
	</div>
<?php endif; ?>

<?php if ($post_javascript_file !== ''): ?>
	<script type="text/javascript" src="<?= Config::PATH_CDN->value(); ?>scripts_form/<?= e($post_javascript_file) ?>"></script>
<?php endif; ?>

<script type="text/javascript">
$(function() {
	document.querySelectorAll(".form-tooltip[title]").forEach(function(el) {
		tippy(el, { content: el.title, placement: "top-start" });
		el.removeAttribute("title");
	});
	<?php if ($focusable): ?>
	$("input:visible:enabled:first").focus();
	<?php endif; ?>
	$('.select-downarrow').bind("click", function () {
		var input = $(this).prev();

		if ($(input).data('is_open')) {
			$(input).autocomplete("close");
			$(input).data('is_open', false);
		} else {
			$(input).autocomplete("search", " ");
			$(input).data('is_open', true);
		}
		$(input).focus();
	});
});
</script>
