<?php

/**
 * @phpstan-type ShapeEntityComment array{
 *     comment_id?: int,
 *     subject_type?: string|null,
 *     subject_id?: int|null,
 *     parent_comment_id?: int|null,
 *     comment?: string|null,
 *     __comment?: string|null,
 * }
 *
 * @property ?int $comment_id (auto_increment)
 * @property ?string $subject_type
 * @property ?int $subject_id
 * @property ?int $parent_comment_id
 * @property ?string $comment
 * @property ?string $__comment
 *
 * @extends SQLEntity<ShapeEntityComment>
 */
class EntityComment extends SQLEntity
{
	public const string TABLE_NAME = 'comments';

	// ============================================================================
	// Custom methods (safe from regeneration)
	// ============================================================================

	public static function addComment(string $subject_type, int $subject_id, ?string $comment, ?int $parent_comment_id = null): int
	{
		$savedata = [
			'subject_type' => $subject_type,
			'subject_id' => $subject_id,
			'__comment' => $comment,
			'parent_comment_id' => $parent_comment_id,
		];

		return static::createFromArray($savedata)->comment_id;
	}

	public static function getComments(string $subject_type, int $subject_id): array
	{
		return DbHelper::selectMany('comments', [
			'subject_type' => $subject_type,
			'subject_id' => $subject_id,
		]);
	}

	public static function getCommentData(int $comment_id): array
	{
		$return = static::findById($comment_id)?->dto();

		if (is_array($return)) {
			return $return;
		} else {
			return [];
		}
	}

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityComment $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityComment $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityComment $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityComment $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|string|array<string, mixed> $id
	 * @param ShapeEntityComment $data
	 */
	public static function updateById(int|string|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityComment $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
